language: generic
sudo: true
dist: bionic

matrix:
  include:
    - env: GHC=ghc-8.8.1
    - env: GHC=ghc-8.6.5
    - env: GHC=ghc-8.4.4
    - env: GHC=ghc-8.2.2
    - env: GHC=ghc-8.0.2

before_install:
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo apt-get update -q
    - sudo apt-get install $GHC cabal-install-3.0 -y
    - PATH=$PATH:/opt/ghc/bin/
    - $GHC --version
    - cabal --version
    - cabal update

script:
    - cabal v1-install --only-dependencies --enable-tests
    - cabal v1-install
    - cabal v1-configure --enable-tests
    - cabal v1-test

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

# vim: expandtab
